### PR TITLE
01 02 regist form input client side validation

### PR DESCRIPTION
**Pull request by kimchirice**
## Rationale

Add input validation before sending data to the server

## Advice for Reviewers & Testing Notes

- rules of current validation
    *  name
      - can not be empty
      - max length is 50 character
      -  currently only accept alphabetic letters, -, ', .
    
    *  Email
      - can not be empty
      - formate check with regex

    *  password
      - can not be empty
      - at least 8 character
      - must contain one numeric and one character of !@#$%^&*`
      - max length is 50 character

    
- Try to give invalid text to see if the validation actually works

## Screenshots:

- https://user-images.githubusercontent.com/36904351/117812716-7eb3e980-b2a5-11eb-866b-e2787779e278.mov

## Task Name

- Issue Title #29 

## Linting Checklist
- [ ] No commented code
- [x] Code Formatted nicely (Prettier)
- [x] PR your own code before you assign reviewers

### CODE REVIEW

**Comment by deBubz** [comment]
why did you use redux for this, what you had before just using plain react functions was fine

**Comment by kimchirice** [comment]
I didnt use Redux. it's useReducer, one of the react hooks

**Comment by pgayoso** [comment]
That's okay

**Comment by kimchirice** [comment]
hello, @deBubz and @xenia11  have you got time to review this PR?? been 8 days

**Review by xenia11 — APPROVED** [review]

**Review by deBubz — CHANGES_REQUESTED** [review]
oh yeah sorry @kimchirice ive ment to wrote this a while ago,
I was just wondering is there any specific reason why you used useReducer instead of useState?
I know that it works, its just unnecessary extra complication added to the page and itll be harder and more time consuming for anyone else that working on it later on. Can you change it back it just regular useState + plain js functions?

**Comment by kimchirice** [comment]
> oh yeah sorry @kimchirice ive ment to wrote this a while ago,
> I was just wondering is there any specific reason why you used useReducer instead of useState?
> I know that it works, its just unnecessary extra complication added to the page and itll be harder and more time consuming for anyone else that working on it later on. Can you change it back it just regular useState + plain js functions?

it's debatable. 

but it's OK, I will roll back to useState hook.

**Comment by kimchirice** [comment]
> > oh yeah sorry @kimchirice ive ment to wrote this a while ago,
> > I was just wondering is there any specific reason why you used useReducer instead of useState?
> > I know that it works, its just unnecessary extra complication added to the page and itll be harder and more time consuming for anyone else that working on it later on. Can you change it back it just regular useState + plain js functions?
> 
> it's debatable.
> 
> but it's OK, I will roll back to useState hook.

mainly to @deBubz, but all feedback is welcome. updated the PR, have a check and let me know your thought.

**Comment by deBubz** [comment]
@kimchirice can you change merging into the `dev` branch

**Review by deBubz — APPROVED** [review]

**Comment by deBubz** [comment]
nvm the previous message, i tested it everything is standalone and works pretty good

**Pull request merged**
