### PR TITLE
Humanitix Integration

### PR DESCRIPTION
**Pull request by xenia11**
## Rationale

This is for testing the git workflow

## Advice for Reviewers & Testing Notes

So, I have already informed Bao that I still have some issues with Humanitix integration. When I console.log the result on the backend, it returns the result from Humanitix, so that's not a problem. Then, when I make an API call from frontend to backend, it enters the function, and then call goes somewhere else. Not sure what's the problem. My guess is that it didn't return well result from backend to frontend. Please take a look.

## Screenshots:

- Add a screenshot or two of your changes, where applicable.

## Task Name

- Issue Title

## Linting Checklist
- [ ] No commented code
- [x] Code Formatted nicely (Prettier)
- [ ] PR your own code before you assign reviewers

### CODE REVIEW

**Comment by xenia11** [comment]
I'll fix with CICD problem, once I figure out what was the problem with  frontend API call.

**Comment by xenia11** [comment]
Hi team. I pushed my latest changes. There is still one bug that I am going to fix later. Otherwise, everything seems to be working nicely. @deBubz @pgayoso @kimchirice, please review it,

**Review by pgayoso — APPROVED** [review]

**Comment by kimchirice** [comment]
> Hi team. I pushed my latest changes. There is still **one bug** that I am going to fix later. Otherwise, everything seems to be working nicely. @deBubz @pgayoso @kimchirice, please review it,

hi @xenia11 trust all is well. 
if there still one bug, could you roll the PR back to draft PR?? 
submit it once the bug you referred to was fixed. thanks

**Comment by xenia11** [comment]
Sure. Will do that.

**Comment by deBubz** [comment]
Hey @xenia11 everything looks great.
But It seems like youre using an older version of `dev` can you have a shot at updating it. it shouldnt take long

so first get the most updated version of `dev` with
`git checkout dev`
`git fech && git pull`

and then switch to your **Humantix**  branch using `git checkout`
get all the lates changes from dev with `git merge dev`
and then double check if all your features still work or not. I think you might have to delete package-lock.json again

One change I reccomend you should do is to ensure the api route requires a login (our convo about `routes.js` last week)
and change the api call in the frontend to use `axios` as that will ensure the token is passed in the call to access the route.

Let me know how it goes.

**Comment by xenia11** [comment]
> Hey @xenia11 everything looks great.
> But It seems like youre using an older version of dev can you have a shot at updating it. it shouldnt take long
> 
> so first get the most updated version of dev with
> git checkout dev
> git fech && git pull
> 
> and then switch to your Humantix branch using git checkout
> get all the lates changes from dev with git merge dev
> and then double check if all your features still work or not. I think you might have to delete package-lock.json again

**Done.**

> One change I reccomend you should do is to ensure the api route requires a login (our convo about routes.js last week)
> and change the api call in the frontend to use axios as that will ensure the token is passed in the call to access the route.
> 
> Let me know how it goes.

**Not yet, it seems like Humanitix is not working properly today. I keep receiving an error from the server (500 status). Tried to figure out what is the issue, then I logged in to my Humanitix and realised that many pages i.e. Humanitix Swagger seems not to be working. `{"message":"Missing Authentication Token"}`**

**Comment by deBubz** [comment]
Hey @xenia11 this task is merged and close for now as im updating `dev` and `master` but still need to address 2 issue

The front-end should only use Axios to call apis (UserEvents.js)

I see your attempt at filtering the latest events but thats not quite it
The filter in `UserEvents.jsx` while it does it job but it is still limited by the call to humanitix in `events.controller.js`

**Pull request merged**
