### PR TITLE
03 05 user events

### PR DESCRIPTION
**Pull request by pgayoso**
## Rationale

Create a slider component for the Events

## Advice for Reviewers & Testing Notes

- Created slideImages constant to test it.
- I suppose that when we charge the user profile, we'll take all this information from the DB. So we need some API to take this.

## Screenshots:

image

## Task Name

- Issue #45

## Linting Checklist
- [ ] No commented code
- [ ] Code Formatted nicely (Prettier)
- [ ] PR your own code before you assign reviewers

### CODE REVIEW

**Review by kimchirice — CHANGES_REQUESTED** [review]
- for components, such as Event,  create a  folder inside the components folder named "event",  move Event.jsx and Event.css to the folders
-  props missing from the Event component 
- in useEvents, Event are imported but never been used
- for list key in React, try to avoid using index

**Comment by xenia11** [comment]
Pablo, what do you think about creating events in Card form? Something similar to Max's courses or cards on the landing page? The slide option seems very nice.

**Review by pgayoso — COMMENTED** [review]
I pushed new code with all the changes.

I created new cards, and fixed the code

**Review by deBubz — APPROVED** [review]
Theres a duplicated file, just be more careful next time

**Pull request merged**
